# Generated by Django 5.2.8 on 2025-11-19 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Simulation', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nx', models.IntegerField(default=5)),
                ('ny', models.IntegerField(default=5)),
                ('voxel_size', models.FloatField(default=0.06, help_text='Side length of a voxel (m)')),
                ('density', models.FloatField(default=1.184, help_text='Density (kg/m^3)')),
                ('specific_heat', models.FloatField(default=1005.0, help_text='Specific Heat (J/kg*K)')),
                ('thermal_conductivity', models.FloatField(default=0.026, help_text='Thermal Conductivity (W/m*K)')),
                ('heater_heat_capacity', models.FloatField(default=1.6, help_text='Heater Heat Capacity (J/K)')),
                ('coupling_mode', models.CharField(choices=[('nearest', 'Nearest Neighbor'), ('distance', 'Distance Based (1/r^2)')], default='nearest', max_length=20)),
                ('q_temp_weight', models.FloatField(default=100.0, help_text='Weight for Temperature Error')),
                ('q_energy_weight', models.FloatField(default=0.1, help_text='Weight for Energy Error')),
                ('r_weight', models.FloatField(default=0.001, help_text='Weight for Control Input')),
                ('p_max', models.FloatField(default=5.0, help_text='Max Power (W)')),
                ('duration', models.FloatField(default=1500.0, help_text='Simulation Duration (s)')),
                ('dt', models.FloatField(default=0.05, help_text='Time Step (s)')),
                ('target_temp_matrix', models.JSONField(default=list)),
                ('temp_ambient', models.FloatField(default=20.0, help_text='Ambient Temperature (C)')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('plot_temp_path', models.CharField(blank=True, max_length=255, null=True)),
                ('plot_input_path', models.CharField(blank=True, max_length=255, null=True)),
                ('plot_heatmap_path', models.CharField(blank=True, max_length=255, null=True)),
                ('rms_error', models.FloatField(blank=True, null=True)),
                ('settling_time', models.FloatField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='main.simulationconfig')),
            ],
        ),
    ]
