# Generated by Django 5.2.8 on 2025-11-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='plot_input_unsat_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
