# Generated by Django 5.2.8 on 2025-11-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_simulationrun_plot_heatmap_anim_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationconfig',
            name='bryson_temp_max',
            field=models.FloatField(default=5.0, help_text="Max temperature deviation for Bryson's rule (°C)"),
        ),
    ]
