# Generated by Django 5.2.8 on 2025-11-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_simulationconfig_bryson_temp_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress_log', models.TextField(blank=True, default='')),
                ('best_q_temp', models.FloatField(blank=True, null=True)),
                ('best_q_energy', models.FloatField(blank=True, null=True)),
                ('best_r', models.FloatField(blank=True, null=True)),
                ('best_score', models.FloatField(blank=True, null=True)),
                ('config_snapshot', models.JSONField()),
            ],
        ),
    ]
